### ISSUE TITLE
What is the appex file?

### ISSUE THREAD

**Issue by jsheely** [patrick-fu/flutter_replay_kit_launcher#1]
Your demo and documentation reference a BroadcastDemoExtension.appex file but I don't know what this file is or what is suppose to be in it. Can you provide a little more information please

**Comment by jsheely** [comment]
Okay I figured it out. Looks like there is a bit of setup you have to do in XCode to wire this up. Your package is just handling the dart side of things.

I think it would still be helpful to link to some documentation or reference this for folks like myself that are coming in from a flutter only perspective and not familiar with how iOS handles this operation

https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/ExtensionCreation.html

**Comment by patrick-fu** [comment]
👍 Thanks for the feedback, the detailed instructions have been updated to the README
