### ISSUE TITLE
No extension display when system broadcast picker show up

### ISSUE THREAD

**Issue by ndthinh1810** [patrick-fu/flutter_replay_kit_launcher#2]
![Screen Shot 2021-02-19 at 14 09 03](https://user-images.githubusercontent.com/52985292/108470151-13690580-72bc-11eb-9429-3a91203a2981.png)
As you can see, I have the extension name 'RikiBroadcastExtension' that I created in runner Xcode project, but it did not show up in the UI when I about to start the broadcast. Can you help me

**Comment by patrick-fu** [comment]
First make sure to use a physical iOS device for debugging, but not simulator.

![Screenshot2021-02-20 10 11 20](https://user-images.githubusercontent.com/20736775/108580339-16203500-7366-11eb-8eae-878d092413ee.png)

Please open `Pods/Development Pods/replay_kit_launcher/[......]/ReplayKitLauncherPlugin.m` with Xcode (your project's `./ios/Runner.workspace`) , and find the code shown on the image, set some breakpoints and then debug in a physical iOS device, check if you click the button to call the dart's `launchReplayKitBroadcast()` method, whether the `line 61` is executed?

**Comment by ndthinh1810** [comment]
![Capture](https://user-images.githubusercontent.com/52985292/108598219-f36e3a80-73be-11eb-81a2-da62e8c6907b.PNG)
i did build it on a physical device, this is the screen when i press the button, my extension did not show. Because of this my server did not receive any stream although the device still let me start broadcasting but nothing happen. So the launch button only call the system broadcast picker to show up

**Comment by patrick-fu** [comment]
It looks weird, could you provide a minimal project that can reproduce this problem?

**Comment by ndthinh1810** [comment]
https://github.com/ndthinh1810/BroadCastFlutter/tree/master this is my project that have the problem, take a look please thank you.

**Comment by patrick-fu** [comment]
![IMG_0036](https://user-images.githubusercontent.com/20736775/108654756-4bfb2000-7504-11eb-8048-4eb7e357ccca.jpg)

Your project runs well on my device (SE2, iOS14.4), I think the problem should be an iOS bug (the broadcast extension will fail to load after repeated debugging, I have also encountered this type of issue), try to delete the app and reboot the device, or try another device.

**Comment by ndthinh1810** [comment]
I tried to build again in ip11 promax and it worked normally. So every device using iOS 12+ should be ok right
