### ISSUE TITLE
Shared preference with app group

### ISSUE THREAD

**Issue by ndthinh1810** [patrick-fu/flutter_replay_kit_launcher#3]
Hello its me again, I have a question. So in my replaykit laucher project, the stream, the state and the configuration of it was all in the broadcast extension sample handler file, I can not access or modify it from flutter view. So can your 'Shared preference with app group' plugin do that. And if it can, how can I do that? Thank you Patrick. Here is the samplehandler.swift
![Screen Shot 2021-02-26 at 16 36 59](https://user-images.githubusercontent.com/52985292/109283010-d8814780-7850-11eb-8e10-ea6fb21331e7.png)

**Comment by patrick-fu** [comment]
For how to use [shared_preference_app_group](https://github.com/patrick-fu/flutter_shared_preference_app_group) plugin, you can refer to this Flutter App project [https://github.com/zegoim/zego-express-example-screen-capture-flutter](https://github.com/zegoim/zego-express-example-screen-capture-flutter), it demonstrates how to implement screen capture and live broadcast on Flutter (Android/iOS).

The `shared_preference_app_group` plugin related code is here:

iOS side: https://github.com/zegoim/zego-express-example-screen-capture-flutter/blob/552996e9e45fce6f771835fe9ccf40c1efb0ba99/ios/BroadcastExtensionFlutter/ZGScreenCaptureManager.m#L187

Dart side: https://github.com/zegoim/zego-express-example-screen-capture-flutter/blob/552996e9e45fce6f771835fe9ccf40c1efb0ba99/lib/manager/internal/screen_capture_manager_impl_ios.dart#L48

**Comment by ndthinh1810** [comment]
I have read your code, but I want to handle stream state while streaming, store the stream state into appgroup user default and then get the stream state in the flutter side was not look like a call back. How do I know when the value of that key change in order to change the stream_state Text in the flutter side. It seem like this shared_preference_app_group did not support observing. Thank you!

**Comment by patrick-fu** [comment]
You can use the cross-process notification feature of iOS, which I used it in the `finishReplayKitBroadcast` method.

- Sender:
    https://github.com/patrick-fu/flutter_replay_kit_launcher/blob/b9d8f9a6f7fe99ff9818bb5717ea8cc0c5e053a3/ios/Classes/ReplayKitLauncherPlugin.m#L21

- Observer:
    https://github.com/zegoim/zego-express-example-screen-capture-flutter/blob/552996e9e45fce6f771835fe9ccf40c1efb0ba99/ios/BroadcastExtensionFlutter/ZGScreenCaptureManager.m#L67

So you can post a notification in the broadcast extension process (the sample handler side) and listen in the main app process (the flutter side)

Further ref: https://stackoverflow.com/a/48558837/7027076

**Comment by ndthinh1810** [comment]
And how do I add observe in the flutter side without CFNotificationCenterAddObserver

**Comment by patrick-fu** [comment]
Simply search for a `CFNotificationCenter` dart warpper plug-in on pub.dev, if not, write one yourself and distribute it to pub/github ^_^

**Comment by ndthinh1810** [comment]
Thank you!

**Comment by ndthinh1810** [comment]
![Uploading Screen Shot 2021-03-05 at 10.01.38.png…]()
