### ISSUE TITLE
Migration to null safety

### ISSUE THREAD

**Issue by Ayman-Kortobaa** [patrick-fu/flutter_replay_kit_launcher#4]
Thanks a lot for this great package!

It would be great if it can be migrated to null safety, it shouldn't take much time after I am done with current project I can make a pull request for it if it's not done by then. 

I just wanted to point out that this package is being used and thanks for developing it and I hope it won't get abandoned :D.

**Comment by patrick-fu** [comment]
😆 Already migrated and published, version 0.3.0
